---
- name: deploy network interface config file
  template:
    src: ifcfg-dev.j2
    dest: /tmp/ifcfg-{{ device }}
  tags: iface

  #- name: bring up deployed interface
  #  shell: ifdown {{ device }} && ifup {{ device }}
  #  tags: iface
  #  ignore_errors: yes
